contacts/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('contact/', views.contact, name="contact"),
    # path('event/', views.event, name="event"),
    path('tech_request/', views.tech_request, name="tech_request")
]

core/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name="index"),
]

creativia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('technologies/', include('technologies.urls')),
    path('events/', include('events.urls')),
    path('contacts/', include('contacts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name = "events"

urlpatterns = [
    path('', views.event, name="event"),
    path('download/', views.download_file, name="download")
]

technologies/urls.py
from django.urls import path
from . import views

app_name = "technology"

urlpatterns = [
    path('', views.get_technologies, name="technologies"),
    path('<int:tech_id>/', views.details, name="details"),
]

templates/partials/_footer.html
<footer class="container-fluid py-5 bg-primary">
    <!-- <div class="row text-white">
        <div class="col-xs-12 col-sm-8 offset-sm-2">
            <div class="d-sm-flex">
                <div class="flex-shrink-0 mt-3">
                    <img src="/static/img/new_logo.png" alt="" width="230" height="65">
                </div>
                <div class="flex-grow-1 ms-3">
                    Kumoh National Institute of Technology, Korea. <br>
                    (39177) 61 Daehak-ro, Gumi-si, Gyeongbuk <br>
                    Fouth Floor, Industry-University Co-operation Building 
                </div>
                <div>
                    <a href="https://www.youtube.com/channel/UCdO-hI6Jyd_sHUvb2Q1vu8A/featured" target="_blank"><i class="fa-brands fa-youtube fa-3x red-color"></i></a>
                </div>
            </div>
        </div>
    </div> -->
    <div class="row text-center">
        <div class="col-sm-4 offset-sm-1 col-md-2 offset-md-2 pt-2">
            <img src="/static/img/new_logo.png" alt="" width="230" height="65">
        </div>
        <div class="col-sm-5 col-md-4">
            <p class="text-sm-start pt-3 pt-sm-1">Kumoh National Institute of Technology, Korea. <br>
                (39177) 61 Daehak-ro, Gumi-si, Gyeongbuk <br>
                Fouth Floor, Industry-University Co-operation Building.</p>
        </div>
        <div class="col-sm-2 col-md-4">
            <a href="https://www.youtube.com/channel/UCdO-hI6Jyd_sHUvb2Q1vu8A/featured" target="_blank"><i class="fa-brands fa-youtube fa-3x text-light"></i></a>
        </div>
    </div>
</footer>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="/static/img/new_logo.png" alt="" width="200" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
        </li> -->
        <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
        <li class="nav-item">
          <a class="nav-link" href="#services">Services</a>
        </li>
        
    
        <!-- <li class="nav-item">
          <a class="nav-link" href="#review">Reviews</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="#contact">Contact</a>
        </li>
          
        
          <!-- <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
          </li>     -->
      </ul>
      
    </div>
  </div>
</nav>

templates/partials/_technologies.html
<!-- <div class="col"> -->
    <div class="card zoom">
        <img src="{{ tech.photo.url }}" alt="" class="card-img-top">
        <div class="card-body text-dark">
            <h5 class="card-title text-center">{{ tech.title }}</h5>
            <p class="card-text">{{ tech.short_description }} </p>
            <hr class="hr">
            <div class="text-center">
                <span><a href="{% url 'technology:details' tech_id=tech.id %}">Read More&raquo;</a></span>
            </div>
        </div>
    </div>
<!-- </div> -->

templates/partials/change.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="/static/img/new_logo.png" alt="" width="200" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <!-- <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'technology:technologies' %}">Technologies</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'events:event' %}">Events</a>
          </li>
    
        <!-- <li class="nav-item">
          <a class="nav-link" href="#review">Reviews</a>
        </li> -->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
        </li>
          
        
          <!-- <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/admin">Admin</a>
          </li>     -->
      </ul>
      
    </div>
  </div>
</nav>